[versions]
junit-jupiter = "5.10.0"
junit-platform = "1.10.0"
mockito = "5.4.0"
jcstress = "0.16"
jmh = "1.34"

[libraries]
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }

jcstress = { group = "org.openjdk.jcstress", name = "jcstress-core", version.ref = "jcstress" }

jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-annotation-processor = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }

[bundles]
junit = [
    "junit-api",
    "junit-engine",
    "junit-platform"
]
testLibraries = [
    "junit-api",
    "junit-engine",
    "junit-platform",
    "mockito"
]
